print("yahoooo! I have created a repository using git and writing code in terminal with nano its cool I hated doing stuff in terminal I kinda liking it now \n expect for the complicated stuffs")
print("Now I am going to add this file without um staging muhaha")
print("I am going to check the difference btw the code before I added this and after using git diff")
print("It seems like you shouldn't commit before using the diff cmd)
print("I am adding to test git add -p")